# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug_linux64
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug_linux64)
  ROBLOXLink_config = debug_linux64

else ifeq ($(config),debug_mac64)
  ROBLOXLink_config = debug_mac64

else ifeq ($(config),release_linux64)
  ROBLOXLink_config = release_linux64

else ifeq ($(config),release_mac64)
  ROBLOXLink_config = release_mac64

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := ROBLOXLink

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

ROBLOXLink:
ifneq (,$(ROBLOXLink_config))
	@echo "==== Building ROBLOXLink ($(ROBLOXLink_config)) ===="
	@${MAKE} --no-print-directory -C . -f ROBLOXLink.make config=$(ROBLOXLink_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f ROBLOXLink.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug_linux64"
	@echo "  debug_mac64"
	@echo "  release_linux64"
	@echo "  release_mac64"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   ROBLOXLink"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"